
package lt.viko.eif.ih.bakery.soap.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BakeriesPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BakeriesPort {


    /**
     * 
     * @param getBakeryRequest
     * @return
     *     returns lt.viko.eif.ih.bakery.soap.client.GetBakeryResponse
     */
    @WebMethod
    @WebResult(name = "getBakeryResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBakeryResponse")
    public GetBakeryResponse getBakery(
        @WebParam(name = "getBakeryRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBakeryRequest")
        GetBakeryRequest getBakeryRequest);

    /**
     * 
     * @param getCartByCustomerRequest
     * @return
     *     returns lt.viko.eif.ih.bakery.soap.client.GetCartByCustomerResponse
     */
    @WebMethod
    @WebResult(name = "getCartByCustomerResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getCartByCustomerResponse")
    public GetCartByCustomerResponse getCartByCustomer(
        @WebParam(name = "getCartByCustomerRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getCartByCustomerRequest")
        GetCartByCustomerRequest getCartByCustomerRequest);

    /**
     * 
     * @param getBakeryByCustomerRequest
     * @return
     *     returns lt.viko.eif.ih.bakery.soap.client.GetBakeryByCustomerResponse
     */
    @WebMethod
    @WebResult(name = "getBakeryByCustomerResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBakeryByCustomerResponse")
    public GetBakeryByCustomerResponse getBakeryByCustomer(
        @WebParam(name = "getBakeryByCustomerRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getBakeryByCustomerRequest")
        GetBakeryByCustomerRequest getBakeryByCustomerRequest);

}
